---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocm-log-forwarder
  namespace: ocm-log-forwarder
  labels:
    app.kubernetes.io/name: ocm-log-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ocm-log-forwarder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ocm-log-forwarder
    spec:
      serviceAccountName: ocm-log-forwarder
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - ocm-log-forwarder
      containers:
        - name: forwarder
          image: ghcr.io/scottd018/ocm-log-forwarder:unstable
          imagePullPolicy: Always
          env:
            # NOTE: present all config options here.  Use these as environment variables 
            #       on the deployment so that changes here result in the app realizing 
            #       those changes by restarting the managed pod.
            - name: OCM_CLUSTER_ID
              value: 22tgckqk9c2ff3jd8ve62p0i2st14vrq
            - name: OCM_POLL_INTERVAL_MINUTES
              value: "1"
            - name: BACKEND_TYPE
              value: elasticsearch
            - name: BACKEND_ES_URL
              value: https://elasticsearch-es-http.elastic-system.svc.cluster.local:9200
            - name: BACKEND_ES_AUTH_TYPE
              value: basic
            - name: BACKEND_ES_INDEX
              value: ocm_service_logs
            - name: DEBUG
              value: "false"
            # WARN: do not change these as changing these have affect of conflicting with
            #       RBAC permissions.
            - name: OCM_SECRET_NAME
              value: ocm-token
            - name: OCM_SECRET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BACKEND_ES_SECRET_NAME
              value: elastic-auth
            - name: BACKEND_ES_SECRET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - "ALL"
            runAsNonRoot: true
            runAsGroup: 0
            seccompProfile: 
              type: RuntimeDefault
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
